
networks:
  mysql-network:
    driver: bridge

services:

  mysql:
    image: mysql:8.0
    command: --default-authentication-plugin=mysql_native_password
    container_name: mysql
    environment:
      MYSQL_DATABASE: mysql_db
      MYSQL_ALLOW_EMPTY_PASSWORD: "yes"
      MYSQL_ROOT_PASSWORD: ""
    ports:
      - "3306:3306"
    volumes:
      - ./mysql:/var/lib/mysql
    networks:
      - mysql-network
